[package]
name = "schematodes"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "schematodes"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.10.5"
pyo3 = "0.18.1"
